apiVersion: v2
name: carbon-aware-kube
description: A Helm chart for the Carbon Aware Kubernetes Operator
type: application
version: 0.1.3
appVersion: "0.1.3"

# Dependencies
dependencies:
  - name: carbon-aware-scheduler
    version: "0.1.0"
    repository: file://../../../scheduler/helm/carbon-aware-scheduler
    condition: carbon-aware-scheduler.local.enabled
