# Default values for carbon-aware-kube operator

# Operator image configuration
image:
  repository: ghcr.io/carbon-aware-kube/operator
  tag: latest
  pullPolicy: IfNotPresent

# Deployment configuration
replicaCount: 1

# Resource limits and requests
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# RBAC configuration
rbac:
  create: true

# Service account configuration
serviceAccount:
  create: true
  name: "controller-manager"

# Node selector for the deployment
nodeSelector: {}

# Tolerations for the deployment
tolerations: []

# Affinity for the deployment
affinity: {}

# Scheduler configuration
scheduler:
  local:
    enabled: true
  external:
    url: ""  # URL of the external scheduler, required if local.enabled is false
