# This rule is not used by the project carbon-aware-kube itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the batch.carbon-aware-kube.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: carbon-aware-kube
    app.kubernetes.io/managed-by: kustomize
  name: carbonawarejob-editor-role
rules:
- apiGroups:
  - batch.carbon-aware-kube.dev
  resources:
  - carbonawarejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.carbon-aware-kube.dev
  resources:
  - carbonawarejobs/status
  verbs:
  - get
