# This rule is not used by the project carbon-aware-kube itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to batch.carbon-aware-kube.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: carbon-aware-kube
    app.kubernetes.io/managed-by: kustomize
  name: carbonawarejob-viewer-role
rules:
- apiGroups:
  - batch.carbon-aware-kube.dev
  resources:
  - carbonawarejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.carbon-aware-kube.dev
  resources:
  - carbonawarejobs/status
  verbs:
  - get
