{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "carbon-aware-kube.fullname" . }}-manager-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carbon-aware-kube.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.carbonaware.dev
  resources:
  - carbonawarejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.carbonaware.dev
  resources:
  - carbonawarejobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.carbonaware.dev
  resources:
  - carbonawarejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
{{- end }}
