apiVersion: v1
entries:
  carbon-aware-scheduler:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-04-18T18:15:35.538747921Z"
    description: A Helm chart for the Carbon Aware Scheduler service
    digest: d6046326cdc5409dd07b8dda6e268f097c8772440cdb319db483be80481812fc
    name: carbon-aware-scheduler
    type: application
    urls:
    - carbon-aware-scheduler-0.1.0.tgz
    version: 0.1.0
generated: "2025-04-18T18:15:35.538329403Z"
