# permissions for end users to edit carbonawarejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: carbonawarejob-editor-role
rules:
- apiGroups:
  - batch.carbon-aware-kube.dev
  resources:
  - carbonawarejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.carbon-aware-kube.dev
  resources:
  - carbonawarejobs/status
  verbs:
  - get
