---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.carbon-aware-kube.dev
  resources:
  - carbonawarejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.carbon-aware-kube.dev
  resources:
  - carbonawarejobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.carbon-aware-kube.dev
  resources:
  - carbonawarejobs/status
  verbs:
  - get
  - patch
  - update
