apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carbon-aware-scheduler.fullname" . }}
  labels:
    {{- include "carbon-aware-scheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "carbon-aware-scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "carbon-aware-scheduler.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.watttime.existingSecret.enabled }}
            - name: WATTIME_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.watttime.existingSecret.name }}
                  key: username
            - name: WATTIME_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.watttime.existingSecret.name }}
                  key: password
            {{- else }}
            - name: WATTIME_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "carbon-aware-scheduler.fullname" . }}-watttime
                  key: username
            - name: WATTIME_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "carbon-aware-scheduler.fullname" . }}-watttime
                  key: password
            {{- end }}
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
