{{- if not .Values.watttime.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carbon-aware-scheduler.fullname" . }}-watttime
  labels:
    {{- include "carbon-aware-scheduler.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.watttime.credentials.username | b64enc | quote }}
  password: {{ .Values.watttime.credentials.password | b64enc | quote }}
{{- end }}
