apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carbon-aware-kube.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carbon-aware-kube.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "carbon-aware-kube.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller-manager
  template:
    metadata:
      labels:
        {{- include "carbon-aware-kube.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller-manager
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: manager
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        args:
        - --leader-elect
        env:
        - name: CARBON_AWARE_SCHEDULER_URL
          value: {{ include "carbon-aware-kube.schedulerUrl" . }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
