{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carbon-aware-kube.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
{{- end }}
