name: Publish Operator Helm Chart to GitHub Pages

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - 'operator/helm/**'
      - '.github/workflows/operator-helm-publish.yml'
      - '.github/workflows/publish-chart.yml'

jobs:
  publish-chart:
    permissions:
      contents: write
    uses: ./.github/workflows/publish-chart.yml
    with:
      chart_path: operator/helm/carbon-aware-kube
    secrets: inherit
