name: Publish a chart to Github Pages

on:
  workflow_call:
    inputs:
        chart_path:
            description: Path to Helm chart
            type: string
            required: true
        update_dependencies:
            description: Update dependencies
            type: boolean
            required: false
            default: false

concurrency:
    group: "publish-chart"
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Download existing index.yaml
        run: |
          mkdir .gh-pages
          curl -sSfL https://carbon-aware-kube.dev/charts/index.yaml -o .gh-pages/index.yaml || true

      - name: Package chart
        run: |
          mkdir -p .packages
          if [[ "${{ inputs.update_dependencies }}" == "true" ]]; then
            helm package --dependency-update ${{ inputs.chart_path }} --destination .packages
          else
            helm package ${{ inputs.chart_path }} --destination .packages
          fi

      - name: Merge index.yaml
        run: |
          if [ -f .gh-pages/index.yaml ]; then
            helm repo index .packages --merge .gh-pages/index.yaml
          else
            helm repo index .packages
          fi

      - name: Copy index and packages to deploy dir
        run: |
          mkdir -p .deploy
          cp .packages/* .deploy/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .deploy
          publish_branch: gh-pages
          destination_dir: charts
