name: Publish Scheduler Helm Chart to GitHub Pages

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - 'scheduler/helm/**'
      - '.github/workflows/scheduler-chart-publish.yml'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: |
          mkdir -p .cr-release-packages
          helm package scheduler/helm/carbon-aware-scheduler --destination .cr-release-packages

      - name: Create Helm repo index
        run: |
          mkdir -p .cr-index
          helm repo index .cr-release-packages --url https://carbon-aware-kube.dev --merge .cr-index/index.yaml || true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .cr-release-packages

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Deploy to GH Pages
        uses: actions/deploy-pages@v4
