name: Publish Scheduler Helm Chart to GitHub Pages

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - 'scheduler/helm/**'
      - '.github/workflows/scheduler-chart-publish.yml'
      - '.github/workflows/publish-chart.yml'

jobs:
  publish-chart:
    permissions:
      contents: write
    uses: ./.github/workflows/publish-chart.yml
    with:
      chart_path: scheduler/helm/carbon-aware-scheduler
    secrets: inherit
