name: Publish Scheduler Helm Chart to GitHub Pages

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - 'scheduler/helm/**'
      - '.github/workflows/scheduler-chart-publish.yml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: |
          mkdir -p .cr-release-packages
          helm package scheduler/helm/carbon-aware-scheduler --destination .cr-release-packages

      - name: Create Helm repo index
        run: |
          mkdir -p .cr-index
          helm repo index .cr-release-packages --url https://carbon-aware-kube.dev --merge .cr-index/index.yaml || true

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .cr-release-packages
          publish_branch: gh-pages

